#!/usr/bin/env php
<?php

if (file_exists(__DIR__ . '/../../autoload.php')) {
    require __DIR__ . '/../../autoload.php';
} else {
    require __DIR__ . '/vendor/autoload.php';
}

define('DATABASE_FILEPATH', __DIR__ . '/storage/database/database.sqlite');

// init
initDotenv();
initDatabase();

// application
$api = initPinboardApi();
$app = initApplication($api);

// init database if it is not already existing
initNotExistingDatabase($app);

$app->run();
